[package]
name = "zrc_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
lalrpop-util = { version = "0.20.1" }
logos = "0.13.0"
regex = "1.10.2"
zrc_diagnostics = { version = "0.1.0", path = "../zrc_diagnostics" }
zrc_utils = { version = "0.1.0", path = "../zrc_utils" }

[build-dependencies]
lalrpop = "0.20.1"
