name: Report a Bug
description: If your compiler has encountered a bug that is not an ICE, report it here.
title: "bug: add your bug title here..."
labels:
    - status/untriaged
    - type/bug
body:
    - type: markdown
      attributes:
          value: >-
              # Thank you for taking your time to report a bug in Zirco!

              Compiler bugs are supposedly rare, so take a second to pat yourself on
              the back! By reporting a bug, you're improving the entire Zirco
              ecosystem as a whole.


              ## Stop! Wait a second.

              If your compiler has failed with a message saying "internal compiler
              error," you are not in the right place. Please [create an ICE
              report](https://github.com/zirco-lang/zrc/issues/new?template=ice.yml)
              instead. Otherwise, let's go on...
    - type: checkboxes
      id: checks
      attributes:
          label: Before we begin...
          description: Please take a second to do the following.
          options:
              - label: I have updated the Zirco toolchain to the latest version
                required: false
              - label: I have searched the issue tracker for duplicates
                required: false
    - type: markdown
      attributes:
          value: >-
              ## Name Your Issue

              Now that we've done that, it's time to give your bug report a good name.
              Summarize the bug you encountered and place it in the name of the issue.


              Once we've done that, it's time to collect some more information!
    - type: textarea
      id: what-happened
      attributes:
          label: What happened?
          description: Please describe the bug you encountered.
      validations:
          required: true
    - type: textarea
      id: version
      attributes:
          label: What version of Zirco are you running?
          description: >-
              Please paste the ENTIRE output of `zrc --version` below, including any
              lines like "tainted files."
          placeholder: zrc version 1.0.0 (...)
      validations:
          required: true
    - type: textarea
      id: repro
      attributes:
          label: How can this bug be reproduced?
          description: >-
              Walk us through the steps. Show us what your `zrc` compilation flags
              were and what code you were compiling, if applicable. Keep it concice
              please!
      validations:
          required: true
    - type: textarea
      id: expected
      attributes:
          label: What behavior did you expect?
          description: >-
              Please tell us what you expected the compiler to do in the above
              scenario.
      validations:
          required: true
    - type: textarea
      id: actual
      attributes:
          label: What actually happened?
          description: >-
              Please describe what really happened and how it differs from your
              expected result.
      validations:
          required: true
    - type: textarea
      id: context
      attributes:
          label: Other Context
          description: >-
              If there is any other context you believe will be helpful in
              investigating this error, please provide it here.
    - type: markdown
      attributes:
          value: >-
              ## Thank you!

              Again, thank you for your time in reporting a bug in Zirco. We will get
              back to you with information on how to at least work around it shortly.
              For now, please wait as we investigate the bug.
