name: "clippy"

on:
    push:
        branches:
            - main
    pull_request:
    merge_group:

jobs:
    clippy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v5
              with:
                  # Make sure the actual branch is checked out when running on pull requests
                  ref: ${{ github.head_ref }}
                  repository: ${{github.event.pull_request.head.repo.full_name || github.repository }}
            - name: Install LLVM 16
              run: |
                  sudo apt-get update
                  sudo apt-get install -y llvm-16 clang-16
            - name: Set up Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
                  override: true
                  components: rustfmt, clippy
            - name: Install Rust problem matchers
              uses: r7kamura/rust-problem-matchers@v1
            - name: Use dependency cache
              uses: Swatinem/rust-cache@v2
            - name: cargo +nightly clippy
              uses: actions-rs/cargo@v1
              with:
                  command: clippy
                  args: --all-targets -- -D warnings
